# Generated by Django 3.0.3 on 2020-05-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('nfc', models.CharField(max_length=1000)),
                ('act_name', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('act_type', models.CharField(max_length=32, unique=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActSta',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('act_id', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('nfc', models.CharField(max_length=1000)),
                ('box_name', models.CharField(max_length=1000)),
                ('box_pos', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoxContent',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('box_id', models.IntegerField()),
                ('thing_name', models.CharField(max_length=1000)),
                ('thing_num', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
