# Generated by Django 3.0.3 on 2020-05-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
                ('content', models.CharField(max_length=1000)),
                ('is_processed', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('friend_id', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushNote',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.IntegerField()),
                ('title', models.CharField(max_length=1000)),
                ('summary', models.CharField(max_length=1000)),
                ('contents', models.CharField(max_length=10000)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='type_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actsta',
            name='is_shared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actsta',
            name='moment_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='active_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_act',
            field=models.CharField(default='1970-01-01', max_length=1000),
        ),
    ]
