# Generated by Django 3.0.3 on 2020-05-29 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guan', '0002_auto_20200525_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='actsta',
            name='shared_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actsta',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
