# Generated by Django 3.0.3 on 2020-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guan', '0003_auto_20200529_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='created_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='updated_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='actsta',
            name='created_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='actsta',
            name='shared_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='actsta',
            name='updated_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='created_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='updated_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='boxcontent',
            name='created_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='boxcontent',
            name='updated_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='friend',
            name='created_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='friend',
            name='updated_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pushnote',
            name='created_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pushnote',
            name='updated_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='created_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='updated_time',
            field=models.BigIntegerField(),
        ),
    ]
